openapi: 3.0.3
info:
  title: Dropbox API
  description: Dropbox API v2 - Combined from multiple Stone definitions
  version: '2.0'
  contact:
    name: Dropbox API
    url: https://www.dropbox.com/developers
servers:
- url: https://api.dropboxapi.com/2
  description: Dropbox API v2
paths:
  /users/get_account:
    post:
      summary: Get information about a user's account.
      operationId: get_account
      security:
      - oauth2:
        - sharing.read
  /users/get_current_account:
    post:
      summary: Get information about the current user's account.
      operationId: get_current_account
      security:
      - oauth2:
        - account_info.read
  /users/get_space_usage:
    post:
      summary: Get the space usage information for the current user's account.
      operationId: get_space_usage
      security:
      - oauth2:
        - account_info.read
  /users/get_account_batch:
    post:
      summary: |-
        Get information about multiple user accounts.  At most 300 accounts may be queried
            per request.
      operationId: get_account_batch
      security:
      - oauth2:
        - sharing.read
  /users/features/get_values:
    post:
      summary: Get a list of feature values that may be configured for the current account.
      operationId: features/get_values
      security:
      - oauth2:
        - account_info.read
  /team/devices/list_member_devices:
    post:
      summary: List all device sessions of a team's member.
      operationId: devices/list_member_devices
      security:
      - oauth2:
        - sessions.list
  /team/devices/list_members_devices:
    post:
      summary: |-
        List all device sessions of a team.

            Permission : Team member file access.
      operationId: devices/list_members_devices
      security:
      - oauth2:
        - sessions.list
  /team/devices/revoke_device_session:
    post:
      summary: Revoke a device session of a team's member.
      operationId: devices/revoke_device_session
      security:
      - oauth2:
        - sessions.modify
  /team/devices/revoke_device_session_batch:
    post:
      summary: Revoke a list of device sessions of team members.
      operationId: devices/revoke_device_session_batch
      security:
      - oauth2:
        - sessions.modify
  /team/groups/list:
    post:
      summary: |-
        Lists groups on a team.

            Permission : Team Information.
      operationId: groups/list
      security:
      - oauth2:
        - groups.read
  /team/groups/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`groups/list`, use this to paginate
            through all groups.

            Permission : Team Information.
      operationId: groups/list/continue
      security:
      - oauth2:
        - groups.read
  /team/groups/get_info:
    post:
      summary: |-
        Retrieves information about one or more groups. Note that the optional field
             :field:`GroupFullInfo.members` is not returned for system-managed groups.

            Permission : Team Information.
      operationId: groups/get_info
      security:
      - oauth2:
        - groups.read
  /team/groups/create:
    post:
      summary: |-
        Creates a new, empty group, with a requested name.

            Permission : Team member management.
      operationId: groups/create
      security:
      - oauth2:
        - groups.write
  /team/groups/delete:
    post:
      summary: |-
        Deletes a group.

            The group is deleted immediately. However the revoking of group-owned resources
            may take additional time.
            Use the :route:`groups/job_status/get` to determine whether this process has completed.

            Permission : Team member management.
      operationId: groups/delete
      security:
      - oauth2:
        - groups.write
  /team/groups/update:
    post:
      summary: |-
        Updates a group's name and/or external ID.

            Permission : Team member management.
      operationId: groups/update
      security:
      - oauth2:
        - groups.write
  /team/groups/members/add:
    post:
      summary: |-
        Adds members to a group.

            The members are added immediately. However the granting of group-owned resources
            may take additional time.
            Use the :route:`groups/job_status/get` to determine whether this process has completed.

            Permission : Team member management.
      operationId: groups/members/add
      security:
      - oauth2:
        - groups.write
  /team/groups/members/remove:
    post:
      summary: |-
        Removes members from a group.

            The members are removed immediately. However the revoking of group-owned resources
            may take additional time.
            Use the :route:`groups/job_status/get` to determine whether this process has completed.

            This method permits removing the only owner of a group, even in cases where this is not
            possible via the web client.

            Permission : Team member management.
      operationId: groups/members/remove
      security:
      - oauth2:
        - groups.write
  /team/groups/members/set_access_type:
    post:
      summary: |-
        Sets a member's access type in a group.

            Permission : Team member management.
      operationId: groups/members/set_access_type
      security:
      - oauth2:
        - groups.write
  /team/groups/members/list:
    post:
      summary: |-
        Lists members of a group.

            Permission : Team Information.
      operationId: groups/members/list
      security:
      - oauth2:
        - groups.read
  /team/groups/members/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`groups/members/list`, use this to paginate
            through all members of the group.

            Permission : Team information.
      operationId: groups/members/list/continue
      security:
      - oauth2:
        - groups.read
  /team/groups/job_status/get:
    post:
      summary: |-
        Once an async_job_id is returned from :route:`groups/delete`,
            :route:`groups/members/add` , or :route:`groups/members/remove`
            use this method to poll the status of granting/revoking
            group members' access to group-owned resources.

            Permission : Team member management.
      operationId: groups/job_status/get
      security:
      - oauth2:
        - groups.write
  /check/user:
    post:
      summary: |-
        This endpoint performs User Authentication, validating the supplied access token,
            and returns the supplied string, to allow you to test your code and connection to the
            Dropbox API. It has no other effect. If you receive an HTTP 200 response with the supplied
            query, it indicates at least part of the Dropbox API infrastructure is working and that the
            access token is valid.
      operationId: user
      security:
      - oauth2:
        - account_info.read
  /check/app:
    post:
      summary: |-
        This endpoint performs App Authentication, validating the supplied app key and secret,
            and returns the supplied string, to allow you to test your code and connection to the
            Dropbox API. It has no other effect. If you receive an HTTP 200 response with the supplied
            query, it indicates at least part of the Dropbox API infrastructure is working and that the
            app key and secret valid.
      operationId: app
      security:
      - oauth2:
        - account_info.read
  /openid/userinfo:
    post:
      summary: |-
        This route is used for refreshing the info that is found in the id_token during the OIDC flow.
            This route doesn't require any arguments and will use the scopes approved for the given access token.
      operationId: userinfo
      security:
      - oauth2:
        - openid
  /sharing/add_file_member:
    post:
      summary: Adds specified members to a file.
      operationId: add_file_member
      security:
      - oauth2:
        - sharing.write
  /sharing/update_file_member:
    post:
      summary: Changes a member's access on a shared file.
      operationId: update_file_member
      security:
      - oauth2:
        - sharing.write
  /sharing/get_file_metadata:
    post:
      summary: Returns shared file metadata.
      operationId: get_file_metadata
      security:
      - oauth2:
        - sharing.read
  /sharing/get_file_metadata/batch:
    post:
      summary: Returns shared file metadata.
      operationId: get_file_metadata/batch
      security:
      - oauth2:
        - sharing.read
  /sharing/list_file_members:
    post:
      summary: |-
        Use to obtain the members who have been invited to a file, both inherited
            and uninherited members.
      operationId: list_file_members
      security:
      - oauth2:
        - sharing.read
  /sharing/list_file_members/batch:
    post:
      summary: |-
        Get members of multiple files at once. The arguments
            to this route are more limited, and the limit on query result size per file
            is more strict. To customize the results more, use the individual file
            endpoint.

            Inherited users and groups are not included in the result, and permissions are not
            returned for this endpoint.
      operationId: list_file_members/batch
      security:
      - oauth2:
        - sharing.read
  /sharing/list_file_members/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`list_file_members` or
            :route:`list_file_members/batch`, use this to paginate through all shared
            file members.
      operationId: list_file_members/continue
      security:
      - oauth2:
        - sharing.read
  /sharing/list_received_files:
    post:
      summary: |-
        Returns a list of all files shared with current user.

             Does not include files the user has received via shared folders, and does
             not include unclaimed invitations.
      operationId: list_received_files
      security:
      - oauth2:
        - sharing.read
  /sharing/list_received_files/continue:
    post:
      summary: Get more results with a cursor from :route:`list_received_files`.
      operationId: list_received_files/continue
      security:
      - oauth2:
        - sharing.read
  /sharing/remove_file_member_2:
    post:
      summary: Removes a specified member from the file.
      operationId: remove_file_member_2
      security:
      - oauth2:
        - sharing.write
  /sharing/relinquish_file_membership:
    post:
      summary: |-
        The current user relinquishes their membership in the designated file.
            Note that the current user may still have inherited access to this file
            through the parent folder.
      operationId: relinquish_file_membership
      security:
      - oauth2:
        - sharing.write
  /sharing/unshare_file:
    post:
      summary: Remove all members from this file. Does not remove inherited members.
      operationId: unshare_file
      security:
      - oauth2:
        - sharing.write
  /team/linked_apps/list_member_linked_apps:
    post:
      summary: |-
        List all linked applications of the team member.

            Note, this endpoint does not list any team-linked applications.
      operationId: linked_apps/list_member_linked_apps
      security:
      - oauth2:
        - sessions.list
  /team/linked_apps/list_members_linked_apps:
    post:
      summary: |-
        List all applications linked to the team members' accounts.

            Note, this endpoint doesn't list any team-linked applications.
      operationId: linked_apps/list_members_linked_apps
      security:
      - oauth2:
        - sessions.list
  /team/linked_apps/revoke_linked_app:
    post:
      summary: Revoke a linked application of the team member.
      operationId: linked_apps/revoke_linked_app
      security:
      - oauth2:
        - sessions.modify
  /team/linked_apps/revoke_linked_app_batch:
    post:
      summary: Revoke a list of linked applications of the team members.
      operationId: linked_apps/revoke_linked_app_batch
      security:
      - oauth2:
        - sessions.modify
  /team_log/get_events:
    post:
      summary: |-
        Retrieves team events. If the result's :field:`GetTeamEventsResult.has_more` field is
            :val:`true`, call :route:`get_events/continue` with the returned cursor to retrieve
            more entries. If end_time is not specified in your request, you may use the returned cursor to
            poll :route:`get_events/continue` for new events.

            Many attributes note 'may be missing due to historical data gap'.

            Note that the file_operations category and & analogous paper events are not available on all
            Dropbox Business :link:`plans /business/plans-comparison`.
            Use :link:`features/get_values /developers/documentation/http/teams#team-features-get_values`
            to check for this feature.

            Permission : Team Auditing.
      operationId: get_events
      security:
      - oauth2:
        - events.read
  /team_log/get_events/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`get_events`, use this to paginate through all events.

            Permission : Team Auditing.
      operationId: get_events/continue
      security:
      - oauth2:
        - events.read
  /team/team_folder/create:
    post:
      summary: |-
        Creates a new, active, team folder with no members. This endpoint can only be used for teams
            that do not already have a shared team space.

            Permission : Team member file access.
      operationId: team_folder/create
      security:
      - oauth2:
        - team_data.content.write
  /team/team_folder/rename:
    post:
      summary: |-
        Changes an active team folder's name.

            Permission : Team member file access.
      operationId: team_folder/rename
      security:
      - oauth2:
        - team_data.content.write
  /team/team_folder/list:
    post:
      summary: |-
        Lists all team folders.

            Permission : Team member file access.
      operationId: team_folder/list
      security:
      - oauth2:
        - team_data.content.read
  /team/team_folder/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`team_folder/list`, use this to paginate
            through all team folders.

            Permission : Team member file access.
      operationId: team_folder/list/continue
      security:
      - oauth2:
        - team_data.content.read
  /team/team_folder/get_info:
    post:
      summary: |-
        Retrieves metadata for team folders.

            Permission : Team member file access.
      operationId: team_folder/get_info
      security:
      - oauth2:
        - team_data.content.read
  /team/team_folder/activate:
    post:
      summary: |-
        Sets an archived team folder's status to active.

            Permission : Team member file access.
      operationId: team_folder/activate
      security:
      - oauth2:
        - team_data.content.write
  /team/team_folder/archive:
    post:
      summary: |-
        Sets an active team folder's status to archived and removes all folder and file members.
            This endpoint cannot be used for teams that have a shared team space.

            Permission : Team member file access.
      operationId: team_folder/archive
      security:
      - oauth2:
        - team_data.content.write
  /team/team_folder/archive/check:
    post:
      summary: |-
        Returns the status of an asynchronous job for archiving a team folder.

            Permission : Team member file access.
      operationId: team_folder/archive/check
      security:
      - oauth2:
        - team_data.content.write
  /team/team_folder/permanently_delete:
    post:
      summary: |-
        Permanently deletes an archived team folder. This endpoint cannot be used for teams
            that have a shared team space.

            Permission : Team member file access.
      operationId: team_folder/permanently_delete
      security:
      - oauth2:
        - team_data.content.write
  /team/team_folder/update_sync_settings:
    post:
      summary: Updates the sync settings on a team folder or its contents.  Use of this endpoint requires that the team has team selective sync enabled.
      operationId: team_folder/update_sync_settings
      security:
      - oauth2:
        - team_data.content.write
  /files/tags/add:
    post:
      summary: Add a tag to an item. A tag is a string. The strings are automatically converted to lowercase letters. No more than 20 tags can be added to a given item.
      operationId: tags/add
      security:
      - oauth2:
        - files.metadata.write
  /files/tags/remove:
    post:
      summary: Remove a tag from an item.
      operationId: tags/remove
      security:
      - oauth2:
        - files.metadata.write
  /files/tags/get:
    post:
      summary: Get list of tags assigned to items.
      operationId: tags/get
      security:
      - oauth2:
        - files.metadata.read
  /auth/token/revoke:
    post:
      summary: |-
        Disables the access token used to authenticate the call.
            If there is a corresponding refresh token for the access token,
            this disables that refresh token, as well as any other access tokens for that refresh token.
      operationId: token/revoke
      security:
      - oauth2:
        - account_info.read
  /auth/token/from_oauth1:
    post:
      summary: Creates an OAuth 2.0 access token from the supplied OAuth 1.0 access token.
      operationId: token/from_oauth1
      security:
      - oauth2:
        - account_info.read
  /file_requests/list:2:
    post:
      summary: |-
        Returns a list of file requests owned by this user. For apps with the app
            folder permission, this will only return file requests with destinations in
            the app folder.
      operationId: list:2
      security:
      - oauth2:
        - file_requests.read
  /file_requests/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`list:2`, use this to paginate through all
            file requests. The cursor must come from a previous call to :route:`list:2` or
            :route:`list/continue`.
      operationId: list/continue
      security:
      - oauth2:
        - file_requests.read
  /file_requests/list:
    post:
      summary: |-
        Returns a list of file requests owned by this user. For apps with the app
            folder permission, this will only return file requests with destinations in
            the app folder.
      operationId: list
      security:
      - oauth2:
        - file_requests.read
  /file_requests/get:
    post:
      summary: Returns the specified file request.
      operationId: get
      security:
      - oauth2:
        - file_requests.read
  /file_requests/create:
    post:
      summary: Creates a file request for this user.
      operationId: create
      security:
      - oauth2:
        - file_requests.write
  /file_requests/update:
    post:
      summary: Update a file request.
      operationId: update
      security:
      - oauth2:
        - file_requests.write
  /file_requests/count:
    post:
      summary: |-
        Returns the total number of file requests owned by this user. Includes both open and
            closed file requests.
      operationId: count
      security:
      - oauth2:
        - file_requests.read
  /file_requests/delete:
    post:
      summary: Delete a batch of closed file requests.
      operationId: delete
      security:
      - oauth2:
        - file_requests.write
  /file_requests/delete_all_closed:
    post:
      summary: Delete all closed file requests owned by this user.
      operationId: delete_all_closed
      security:
      - oauth2:
        - file_requests.write
  /paper/docs/folder_users/list:
    post:
      summary: |-
        Lists the users who are explicitly invited to the Paper folder in which the Paper doc
            is contained. For private folders all users (including owner) shared on the folder
            are listed and for team folders all non-team users shared on the folder are returned.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/folder_users/list
      security:
      - oauth2:
        - sharing.read
  /paper/docs/folder_users/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`docs/folder_users/list`, use this to
            paginate through all users on the Paper folder.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/folder_users/list/continue
      security:
      - oauth2:
        - sharing.read
  /paper/docs/sharing_policy/get:
    post:
      summary: |-
        Gets the default sharing policy for the given Paper doc.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/sharing_policy/get
      security:
      - oauth2:
        - sharing.read
  /paper/docs/sharing_policy/set:
    post:
      summary: |-
        Sets the default sharing policy for the given Paper doc. The default 'team_sharing_policy'
            can be changed only by teams, omit this field for personal accounts.

            The 'public_sharing_policy' policy can't be set to the value 'disabled' because this setting
            can be changed only via the team admin console.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/sharing_policy/set
      security:
      - oauth2:
        - sharing.write
  /paper/docs/archive:
    post:
      summary: |-
        Marks the given Paper doc as archived.

            This action can be performed or undone by anyone with edit permissions to the doc.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            This endpoint will be retired in September 2020. Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for more information.
      operationId: docs/archive
      security:
      - oauth2:
        - files.content.write
  /paper/docs/permanently_delete:
    post:
      summary: |-
        Permanently deletes the given Paper doc. This operation is final as the doc
            cannot be recovered.

            This action can be performed only by the doc owner.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/permanently_delete
      security:
      - oauth2:
        - files.permanent_delete
  /paper/docs/download:
    post:
      summary: |-
        Exports and downloads Paper doc either as HTML or markdown.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/download
      security:
      - oauth2:
        - files.content.read
  /paper/docs/get_folder_info:
    post:
      summary: |-
        Retrieves folder information for the given Paper doc. This includes:

              - folder sharing policy; permissions for subfolders are set by the top-level folder.

              - full 'filepath', i.e. the list of folders (both folderId and folderName) from
                the root folder to the folder directly containing the Paper doc.


            If the Paper doc is not in any folder (aka unfiled) the response will be empty.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/get_folder_info
      security:
      - oauth2:
        - sharing.read
  /paper/docs/users/add:
    post:
      summary: |-
        Allows an owner or editor to add users to a Paper doc or change their permissions
            using their email address or Dropbox account ID.

            The doc owner's permissions cannot be changed.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/users/add
      security:
      - oauth2:
        - sharing.write
  /paper/docs/users/remove:
    post:
      summary: |-
        Allows an owner or editor to remove users from a Paper doc using their email address or
            Dropbox account ID.

            The doc owner cannot be removed.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/users/remove
      security:
      - oauth2:
        - sharing.write
  /paper/docs/users/list:
    post:
      summary: |-
        Lists all users who visited the Paper doc or users with explicit access. This call
            excludes users who have been removed. The list is sorted by the date of the visit or
            the share date.

            The list will include both users, the explicitly shared ones as well as those
            who came in using the Paper url link.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/users/list
      security:
      - oauth2:
        - sharing.read
  /paper/docs/users/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`docs/users/list`, use this to
            paginate through all users on the Paper doc.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/users/list/continue
      security:
      - oauth2:
        - sharing.read
  /paper/docs/list:
    post:
      summary: |-
        Return the list of all Paper docs according to the argument specifications. To iterate
            over through the full pagination, pass the cursor to :route:`docs/list/continue`.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/list
      security:
      - oauth2:
        - files.metadata.read
  /paper/docs/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`docs/list`, use this to
            paginate through all Paper doc.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: docs/list/continue
      security:
      - oauth2:
        - files.metadata.read
  /paper/docs/create:
    post:
      summary: |-
        Creates a new Paper doc with the provided content.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            This endpoint will be retired in September 2020. Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for more information.
      operationId: docs/create
      security:
      - oauth2:
        - files.content.write
  /paper/docs/update:
    post:
      summary: |-
        Updates an existing Paper doc with the provided content.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            This endpoint will be retired in September 2020. Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for more information.
      operationId: docs/update
      security:
      - oauth2:
        - files.content.write
  /paper/folders/create:
    post:
      summary: |-
        Create a new Paper folder with the provided info.

            Note that this endpoint will continue to work for content created by users on the older version of Paper. To check which version of Paper a user is on, use /users/features/get_values. If the paper_as_files feature is enabled, then the user is running the new version of Paper.

            Refer to the :link:`Paper Migration Guide https://www.dropbox.com/lp/developers/reference/paper-migration-guide` for migration information.
      operationId: folders/create
      security:
      - oauth2:
        - files.content.write
  /team/namespaces/list:
    post:
      summary: |-
        Returns a list of all team-accessible namespaces. This list includes team folders,
            shared folders containing team members, team members' home namespaces, and team members'
            app folders. Home namespaces and app folders are always owned by this team or members of the
            team, but shared folders may be owned by other users or other teams. Duplicates may occur in the
            list.
      operationId: namespaces/list
      security:
      - oauth2:
        - team_data.member
  /team/namespaces/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`namespaces/list`, use this to paginate
            through all team-accessible namespaces. Duplicates may occur in the list.
      operationId: namespaces/list/continue
      security:
      - oauth2:
        - team_data.member
  /team/get_info:
    post:
      summary: Retrieves information about a team.
      operationId: get_info
      security:
      - oauth2:
        - team_info.read
  /team/token/get_authenticated_admin:
    post:
      summary: Returns the member profile of the admin who generated the team access token used to make the call.
      operationId: token/get_authenticated_admin
      security:
      - oauth2:
        - team_info.read
  /team/features/get_values:
    post:
      summary: |-
        Get the values for one or more featues. This route allows you to check your account's
            capability for what feature you can access or what value you have for certain features.

            Permission : Team information.
      operationId: features/get_values
      security:
      - oauth2:
        - team_info.read
  /team/properties/template/add:
    post:
      summary: 'Permission : Team member file access.'
      operationId: properties/template/add
      security:
      - oauth2:
        - files.team_metadata.write
  /team/properties/template/update:
    post:
      summary: 'Permission : Team member file access.'
      operationId: properties/template/update
      security:
      - oauth2:
        - files.team_metadata.write
  /team/properties/template/get:
    post:
      summary: 'Permission : Team member file access. The scope for the route is files.team_metadata.write.'
      operationId: properties/template/get
      security:
      - oauth2:
        - files.team_metadata.write
  /team/properties/template/list:
    post:
      summary: 'Permission : Team member file access. The scope for the route is files.team_metadata.write.'
      operationId: properties/template/list
      security:
      - oauth2:
        - files.team_metadata.write
  /team/reports/get_storage:
    post:
      summary: |-
        Retrieves reporting data about a team's storage usage.
            Deprecated: Will be removed on July 1st 2021.
      operationId: reports/get_storage
      security:
      - oauth2:
        - team_info.read
  /team/reports/get_activity:
    post:
      summary: |-
        Retrieves reporting data about a team's user activity.
            Deprecated: Will be removed on July 1st 2021.
      operationId: reports/get_activity
      security:
      - oauth2:
        - team_info.read
  /team/reports/get_membership:
    post:
      summary: |-
        Retrieves reporting data about a team's membership.
            Deprecated: Will be removed on July 1st 2021.
      operationId: reports/get_membership
      security:
      - oauth2:
        - team_info.read
  /team/reports/get_devices:
    post:
      summary: |-
        Retrieves reporting data about a team's linked devices.
            Deprecated: Will be removed on July 1st 2021.
      operationId: reports/get_devices
      security:
      - oauth2:
        - team_info.read
  /contacts/delete_manual_contacts:
    post:
      summary: |-
        Removes all manually added contacts.
            You'll still keep contacts who are on your team or who you imported.
            New contacts will be added when you share.
      operationId: delete_manual_contacts
      security:
      - oauth2:
        - contacts.write
  /contacts/delete_manual_contacts_batch:
    post:
      summary: Removes manually added contacts from the given list.
      operationId: delete_manual_contacts_batch
      security:
      - oauth2:
        - contacts.write
  /files/get_metadata:
    post:
      summary: |-
        Returns the metadata for a file or folder. This is an alpha endpoint
            compatible with the properties API.

            Note: Metadata for the root folder is unsupported.
      operationId: get_metadata
      security:
      - oauth2:
        - files.metadata.read
  /files/list_folder/longpoll:
    post:
      summary: |-
        A longpoll endpoint to wait for changes on an account. In conjunction with
            :route:`list_folder/continue`, this call gives you a low-latency way to
            monitor an account for file changes. The connection will block until there
            are changes available or a timeout occurs. This endpoint is useful mostly
            for client-side apps. If you're looking for server-side notifications,
            check out our
            :link:`webhooks documentation https://www.dropbox.com/developers/reference/webhooks`.
      operationId: list_folder/longpoll
      security:
      - oauth2:
        - files.metadata.read
  /files/list_folder:
    post:
      summary: |-
        Starts returning the contents of a folder. If the result's :field:`ListFolderResult.has_more`
            field is :val:`true`, call :route:`list_folder/continue` with the returned
            :field:`ListFolderResult.cursor` to retrieve more entries.

            If you're using :field:`ListFolderArg.recursive` set to :val:`true` to keep a local cache of
            the contents of a Dropbox account, iterate through each entry in order and process them as
            follows to keep your local state in sync:

            For each :type:`FileMetadata`, store the new entry at the given path in your local state. If the
            required parent folders don't exist yet, create them. If there's already something else at the
            given path, replace it and remove all its children.

            For each :type:`FolderMetadata`, store the new entry at the given path in your local state. If
            the required parent folders don't exist yet, create them. If there's already something else at
            the given path, replace it but leave the children as they are. Check the new entry's
            :field:`FolderSharingInfo.read_only` and set all its children's read-only statuses to match.

            For each :type:`DeletedMetadata`, if your local state has something at the given path, remove it
            and all its children. If there's nothing at the given path, ignore this entry.

            Note: :type:`auth.RateLimitError` may be returned if multiple :route:`list_folder` or
            :route:`list_folder/continue` calls with same parameters are made simultaneously by same
            API app for same user. If your app implements retry logic, please hold off the retry until
            the previous request finishes.
      operationId: list_folder
      security:
      - oauth2:
        - files.metadata.read
  /files/list_folder/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`list_folder`, use this to paginate through all
            files and retrieve updates to the folder, following the same rules as documented for
            :route:`list_folder`.
      operationId: list_folder/continue
      security:
      - oauth2:
        - files.metadata.read
  /files/list_folder/get_latest_cursor:
    post:
      summary: |-
        A way to quickly get a cursor for the folder's state. Unlike :route:`list_folder`,
            :route:`list_folder/get_latest_cursor` doesn't return any entries. This endpoint is for app
            which only needs to know about new files and modifications and doesn't need to know about
            files that already exist in Dropbox.
      operationId: list_folder/get_latest_cursor
      security:
      - oauth2:
        - files.metadata.read
  /files/download:
    post:
      summary: Download a file from a user's Dropbox.
      operationId: download
      security:
      - oauth2:
        - files.content.read
  /files/download_zip:
    post:
      summary: |-
        Download a folder from the user's Dropbox, as a zip file. The folder must be less than 20 GB
            in size and any single file within must be less than 4 GB in size. The resulting zip must have
            fewer than 10,000 total file and folder entries, including the top level folder. The input
            cannot be a single file.

            Note: this endpoint does not support HTTP range requests.
      operationId: download_zip
      security:
      - oauth2:
        - files.content.read
  /files/export:
    post:
      summary: |-
        Export a file from a user's Dropbox. This route only supports exporting files that cannot be downloaded directly
             and whose :field:`ExportResult.file_metadata` has :field:`ExportInfo.export_as` populated.
      operationId: export
      security:
      - oauth2:
        - files.content.read
  /files/upload_session/start_batch:
    post:
      summary: |-
        This route starts batch of upload_sessions. Please refer to `upload_session/start` usage.

            Calls to this endpoint will count as data transport calls for any Dropbox
            Business teams with a limit on the number of data transport calls allowed
            per month. For more information, see the :link:`Data transport limit page
            https://www.dropbox.com/developers/reference/data-transport-limit`.
      operationId: upload_session/start_batch
      security:
      - oauth2:
        - files.content.write
  /files/upload_session/start:
    post:
      summary: |-
        Upload sessions allow you to upload a single file in one or more
            requests, for example where the size of the file is greater than 150
            MB.  This call starts a new upload session with the given data. You
            can then use :route:`upload_session/append:2` to add more data and
            :route:`upload_session/finish` to save all the data to a file in
            Dropbox.

            A single request should not upload more than 150 MB. The maximum size of
            a file one can upload to an upload session is 350 GB.

            An upload session can be used for a maximum of 7 days. Attempting
            to use an :field:`UploadSessionStartResult.session_id` with
            :route:`upload_session/append:2` or :route:`upload_session/finish` more
            than 7 days after its creation will return a
            :field:`UploadSessionLookupError.not_found`.

            Calls to this endpoint will count as data transport calls for any Dropbox
            Business teams with a limit on the number of data transport calls allowed
            per month. For more information, see the :link:`Data transport limit page
            https://www.dropbox.com/developers/reference/data-transport-limit`.

            By default, upload sessions require you to send content of the file in sequential order via
            consecutive :route:`upload_session/start`, :route:`upload_session/append:2`,
            :route:`upload_session/finish` calls. For better performance, you can instead optionally use
            a :field:`UploadSessionType.concurrent` upload session. To start a new concurrent session,
            set :field:`UploadSessionStartArg.session_type` to :field:`UploadSessionType.concurrent`.
            After that, you can send file data in concurrent :route:`upload_session/append:2` requests.
            Finally finish the session with :route:`upload_session/finish`.

            There are couple of constraints with concurrent sessions to make them work. You can not send
            data with :route:`upload_session/start` or :route:`upload_session/finish` call, only with
            :route:`upload_session/append:2` call. Also data uploaded in :route:`upload_session/append:2`
            call must be multiple of 4194304 bytes (except for last :route:`upload_session/append:2` with
            :field:`UploadSessionStartArg.close` to :val:`true`, that may contain any remaining data).
      operationId: upload_session/start
      security:
      - oauth2:
        - files.content.write
  /files/upload_session/append:2:
    post:
      summary: |-
        Append more data to an upload session.

            A single request should not upload more than 150 MB. The maximum size of
            a file one can upload to an upload session is 350 GB.

            Calls to this endpoint will count as data transport calls for any Dropbox
            Business teams with a limit on the number of data transport calls allowed
            per month. For more information, see the :link:`Data transport limit page https://www.dropbox.com/developers/reference/data-transport-limit`.
      operationId: upload_session/append:2
      security:
      - oauth2:
        - files.content.write
  /files/upload_session/finish:
    post:
      summary: |-
        Finish an upload session and save the uploaded data to the given file
            path.

            A single request should not upload more than 150 MB. The maximum size of
            a file one can upload to an upload session is 350 GB.

            Calls to this endpoint will count as data transport calls for any Dropbox
            Business teams with a limit on the number of data transport calls allowed
            per month. For more information, see the :link:`Data transport limit page https://www.dropbox.com/developers/reference/data-transport-limit`.
      operationId: upload_session/finish
      security:
      - oauth2:
        - files.content.write
  /files/upload:
    post:
      summary: |-
        Create a new file with the contents provided in the request. Note that the
            behavior of this alpha endpoint is unstable and subject to change.

            Do not use this to upload a file larger than 150 MB. Instead, create an
            upload session with :route:`upload_session/start`.
      operationId: upload
      security:
      - oauth2:
        - files.content.write
  /files/upload_session/finish_batch:2:
    post:
      summary: |-
        This route helps you commit many files at once into a user's Dropbox. Use
            :route:`upload_session/start` and :route:`upload_session/append:2` to
            upload file contents. We recommend uploading many files in parallel to increase
            throughput. Once the file contents have been uploaded, rather than calling
            :route:`upload_session/finish`, use this route to finish all your upload sessions
            in a single request.

            :field:`UploadSessionStartArg.close` or :field:`UploadSessionAppendArg.close`
            needs to be true for the last
            :route:`upload_session/start` or :route:`upload_session/append:2` call of each upload session. The maximum
            size of a file one can upload to an upload session is 350 GB.

            We allow up to 1000 entries in a single request.

            Calls to this endpoint will count as data transport calls for any Dropbox
            Business teams with a limit on the number of data transport calls allowed
            per month. For more information, see the :link:`Data transport limit page https://www.dropbox.com/developers/reference/data-transport-limit`.
      operationId: upload_session/finish_batch:2
      security:
      - oauth2:
        - files.content.write
  /files/upload_session/finish_batch/check:
    post:
      summary: |-
        Returns the status of an asynchronous job for :route:`upload_session/finish_batch`. If
            success, it returns list of result for each entry.
      operationId: upload_session/finish_batch/check
      security:
      - oauth2:
        - files.content.write
  /files/search:2:
    post:
      summary: |-
        Searches for files and folders.

            Note: :route:`search:2` along with :route:`search/continue:2` can only be used to
            retrieve a maximum of 10,000 matches.

            Recent changes may not immediately be reflected in search results due to a short delay in indexing.
            Duplicate results may be returned across pages. Some results may not be returned.
      operationId: search:2
      security:
      - oauth2:
        - files.metadata.read
  /files/search/continue:2:
    post:
      summary: |-
        Fetches the next page of search results returned from :route:`search:2`.

            Note: :route:`search:2` along with :route:`search/continue:2` can only be used to
            retrieve a maximum of 10,000 matches.

            Recent changes may not immediately be reflected in search results due to a short delay in indexing.
            Duplicate results may be returned across pages. Some results may not be returned.
      operationId: search/continue:2
      security:
      - oauth2:
        - files.metadata.read
  /files/create_folder:2:
    post:
      summary: Create a folder at a given path.
      operationId: create_folder:2
      security:
      - oauth2:
        - files.content.write
  /files/create_folder_batch:
    post:
      summary: |-
        Create multiple folders at once.

            This route is asynchronous for large batches, which returns a job ID immediately and runs
            the create folder batch asynchronously. Otherwise, creates the folders and returns the result
            synchronously for smaller inputs. You can force asynchronous behaviour by using the
            :field:`CreateFolderBatchArg.force_async` flag.  Use :route:`create_folder_batch/check` to check
            the job status.
      operationId: create_folder_batch
      security:
      - oauth2:
        - files.content.write
  /files/create_folder_batch/check:
    post:
      summary: |-
        Returns the status of an asynchronous job for :route:`create_folder_batch`. If
            success, it returns list of result for each entry.
      operationId: create_folder_batch/check
      security:
      - oauth2:
        - files.content.write
  /files/delete:2:
    post:
      summary: |-
        Delete the file or folder at a given path.

            If the path is a folder, all its contents will be deleted too.

            A successful response indicates that the file or folder was deleted. The returned metadata will
            be the corresponding :type:`FileMetadata` or :type:`FolderMetadata` for the item at time of
            deletion, and not a :type:`DeletedMetadata` object.
      operationId: delete:2
      security:
      - oauth2:
        - files.content.write
  /files/delete_batch:
    post:
      summary: |-
        Delete multiple files/folders at once.

            This route is asynchronous, which returns a job ID immediately and runs
            the delete batch asynchronously. Use :route:`delete_batch/check` to check
            the job status.
      operationId: delete_batch
      security:
      - oauth2:
        - files.content.write
  /files/delete_batch/check:
    post:
      summary: |-
        Returns the status of an asynchronous job for :route:`delete_batch`. If
            success, it returns list of result for each entry.
      operationId: delete_batch/check
      security:
      - oauth2:
        - files.content.write
  /files/permanently_delete:
    post:
      summary: |-
        Permanently delete the file or folder at a given path
            (see https://www.dropbox.com/en/help/40).

            If the given file or folder is not yet deleted, this route will first delete it.
            It is possible for this route to successfully delete, then fail to permanently
            delete.

            Note: This endpoint is only available for Dropbox Business apps.
      operationId: permanently_delete
      security:
      - oauth2:
        - files.permanent_delete
  /files/copy:2:
    post:
      summary: |-
        Copy a file or folder to a different location in the user's Dropbox.

            If the source path is a folder all its contents will be copied.
      operationId: copy:2
      security:
      - oauth2:
        - files.content.write
  /files/copy_batch:2:
    post:
      summary: |-
        Copy multiple files or folders to different locations at once in the
            user's Dropbox.

            This route will return job ID immediately and do the async copy job in
            background. Please use :route:`copy_batch/check:1` to check the job status.
      operationId: copy_batch:2
      security:
      - oauth2:
        - files.content.write
  /files/copy_batch/check:2:
    post:
      summary: |-
        Returns the status of an asynchronous job for :route:`copy_batch:1`. If
            success, it returns list of results for each entry.
      operationId: copy_batch/check:2
      security:
      - oauth2:
        - files.content.write
  /files/move:2:
    post:
      summary: |-
        Move a file or folder to a different location in the user's Dropbox.

            If the source path is a folder all its contents will be moved.
      operationId: move:2
      security:
      - oauth2:
        - files.content.write
  /files/move_batch:2:
    post:
      summary: |-
        Move multiple files or folders to different locations at once in the
            user's Dropbox.

            This route will return job ID immediately and do the async moving job in
            background. Please use :route:`move_batch/check:1` to check the job status.
      operationId: move_batch:2
      security:
      - oauth2:
        - files.content.write
  /files/move_batch/check:2:
    post:
      summary: |-
        Returns the status of an asynchronous job for :route:`move_batch:1`. If
            success, it returns list of results for each entry.
      operationId: move_batch/check:2
      security:
      - oauth2:
        - files.content.write
  /files/get_thumbnail:
    post:
      summary: |-
        Get a thumbnail for an image.

            This method currently supports files with the following file extensions:
            jpg, jpeg, png, tiff, tif, gif, webp, ppm and bmp. Photos that are larger than 20MB
            in size won't be converted to a thumbnail.
      operationId: get_thumbnail
      security:
      - oauth2:
        - files.content.read
  /files/get_thumbnail_batch:
    post:
      summary: |-
        Get thumbnails for a list of images. We allow up to 25 thumbnails in a single batch.

            This method currently supports files with the following file extensions:
            jpg, jpeg, png, tiff, tif, gif, webp, ppm and bmp. Photos that are larger than 20MB
            in size won't be converted to a thumbnail.
      operationId: get_thumbnail_batch
      security:
      - oauth2:
        - files.content.read
  /files/get_thumbnail:2:
    post:
      summary: |-
        Get a thumbnail for an image.

            This method currently supports files with the following file extensions:
            jpg, jpeg, png, tiff, tif, gif, webp, ppm and bmp. Photos that are larger than 20MB
            in size won't be converted to a thumbnail.
      operationId: get_thumbnail:2
      security:
      - oauth2:
        - files.content.read
  /files/get_preview:
    post:
      summary: |-
        Get a preview for a file.

            Currently, PDF previews are generated for files with the following extensions:
            .ai, .doc, .docm, .docx, .eps, .gdoc, .gslides, .odp, .odt, .pps, .ppsm, .ppsx, .ppt, .pptm, .pptx, .rtf.

            HTML previews are generated for files with the following extensions: .csv, .ods, .xls, .xlsm, .gsheet, .xlsx.

            Other formats will return an unsupported extension error.
      operationId: get_preview
      security:
      - oauth2:
        - files.content.read
  /files/list_revisions:
    post:
      summary: |-
        Returns revisions for files based on a file path or a file id. The file path or file id is
            identified from the latest file entry at the given file path or id. This end point allows your
            app to query either by file path or file id by setting the mode parameter appropriately.

            In the :field:`ListRevisionsMode.path` (default) mode, all revisions at the same
            file path as the latest file entry are
            returned. If revisions with the same file id are desired, then mode must be set to
            :field:`ListRevisionsMode.id`. The :field:`ListRevisionsMode.id` mode is useful to retrieve
            revisions for a given file across moves or renames.
      operationId: list_revisions
      security:
      - oauth2:
        - files.metadata.read
  /files/restore:
    post:
      summary: Restore a specific revision of a file to the given path.
      operationId: restore
      security:
      - oauth2:
        - files.content.write
  /files/get_temporary_link:
    post:
      summary: |-
        Get a temporary link to stream content of a file. This link will expire in four hours and
            afterwards you will get 410 Gone. This URL should not be used to display content directly
            in the browser. The Content-Type of the link is determined automatically by the file's mime type.
      operationId: get_temporary_link
      security:
      - oauth2:
        - files.content.read
  /files/get_temporary_upload_link:
    post:
      summary: "Get a one-time use temporary upload link to upload a file to a Dropbox location.\n\n\n    This endpoint acts as a delayed :route:`upload`. The returned temporary upload link may be used\n    to make a POST request with the data to be uploaded. The upload will then be perfomed with the\n    :type:`CommitInfo` previously provided to :route:`get_temporary_upload_link` but evaluated only\n    upon consumption. Hence, errors stemming from invalid :type:`CommitInfo` with respect to the[...]"
      operationId: get_temporary_upload_link
      security:
      - oauth2:
        - files.content.write
  /files/copy_reference/get:
    post:
      summary: |-
        Get a copy reference to a file or folder. This reference string can be used to
            save that file or folder to another user's Dropbox by passing it to
            :route:`copy_reference/save`.
      operationId: copy_reference/get
      security:
      - oauth2:
        - files.content.write
  /files/copy_reference/save:
    post:
      summary: Save a copy reference returned by :route:`copy_reference/get` to the user's Dropbox.
      operationId: copy_reference/save
      security:
      - oauth2:
        - files.content.write
  /files/save_url:
    post:
      summary: |-
        Save the data from a specified URL into a file in user's Dropbox.

            Note that the transfer from the URL must complete within 15 minutes, or the
            operation will time out and the job will fail.

            If the given path already exists, the file will be renamed to avoid the
            conflict (e.g. myfile (1).txt).
      operationId: save_url
      security:
      - oauth2:
        - files.content.write
  /files/save_url/check_job_status:
    post:
      summary: Check the status of a :route:`save_url` job.
      operationId: save_url/check_job_status
      security:
      - oauth2:
        - files.content.write
  /files/properties/add:
    post:
      summary: Execute properties/add
      operationId: properties/add
      security:
      - oauth2:
        - files.metadata.write
  /files/properties/overwrite:
    post:
      summary: Execute properties/overwrite
      operationId: properties/overwrite
      security:
      - oauth2:
        - files.metadata.write
  /files/properties/update:
    post:
      summary: Execute properties/update
      operationId: properties/update
      security:
      - oauth2:
        - files.metadata.write
  /files/properties/remove:
    post:
      summary: Execute properties/remove
      operationId: properties/remove
      security:
      - oauth2:
        - files.metadata.write
  /files/properties/template/get:
    post:
      summary: Execute properties/template/get
      operationId: properties/template/get
      security:
      - oauth2:
        - files.metadata.read
  /files/properties/template/list:
    post:
      summary: Execute properties/template/list
      operationId: properties/template/list
      security:
      - oauth2:
        - files.metadata.read
  /files/lock_file_batch:
    post:
      summary: "\n    Lock the files at the given paths. A locked file will be writable only by the lock holder.\n    A successful response indicates that the file has been locked. Returns a list of the\n    locked file paths and their metadata after this operation.\n    "
      operationId: lock_file_batch
      security:
      - oauth2:
        - files.content.write
  /files/unlock_file_batch:
    post:
      summary: "\n    Unlock the files at the given paths. A locked file can only be unlocked by the lock holder\n    or, if a business account, a team admin. A successful response indicates that the file has\n    been unlocked. Returns a list of the unlocked file paths and their metadata after\n    this operation.\n    "
      operationId: unlock_file_batch
      security:
      - oauth2:
        - files.content.write
  /files/get_file_lock_batch:
    post:
      summary: "\n    Return the lock metadata for the given list of paths.\n    "
      operationId: get_file_lock_batch
      security:
      - oauth2:
        - files.content.read
  /files/paper/create:
    post:
      summary: "\n    Creates a new Paper doc with the provided content.\n    "
      operationId: paper/create
      security:
      - oauth2:
        - files.content.write
  /files/paper/update:
    post:
      summary: "\n    Updates an existing Paper doc with the provided content.\n    "
      operationId: paper/update
      security:
      - oauth2:
        - files.content.write
  /file_properties/properties/add:
    post:
      summary: |-
        Add property groups to a Dropbox file. See :route:`templates/add_for_user` or
            :route:`templates/add_for_team` to create new templates.
      operationId: properties/add
      security:
      - oauth2:
        - files.metadata.write
  /file_properties/properties/overwrite:
    post:
      summary: |-
        Overwrite property groups associated with a file. This endpoint should be used
            instead of :route:`properties/update` when property groups are being updated via a
            "snapshot" instead of via a "delta". In other words, this endpoint will delete all
            omitted fields from a property group, whereas :route:`properties/update` will only
            delete fields that are explicitly marked for deletion.
      operationId: properties/overwrite
      security:
      - oauth2:
        - files.metadata.write
  /file_properties/properties/update:
    post:
      summary: |-
        Add, update or remove properties associated with the supplied file and templates.
            This endpoint should be used instead of :route:`properties/overwrite` when property groups
            are being updated via a "delta" instead of via a "snapshot" . In other words, this endpoint
            will not delete any omitted fields from a property group, whereas :route:`properties/overwrite`
            will delete any fields that are omitted from a property group.
      operationId: properties/update
      security:
      - oauth2:
        - files.metadata.write
  /file_properties/properties/remove:
    post:
      summary: |-
        Permanently removes the specified property group from the file. To remove specific property field key
            value pairs, see :route:`properties/update`.
            To update a template, see
            :route:`templates/update_for_user` or :route:`templates/update_for_team`.
            To remove a template, see
            :route:`templates/remove_for_user` or :route:`templates/remove_for_team`.
      operationId: properties/remove
      security:
      - oauth2:
        - files.metadata.write
  /file_properties/templates/add_for_user:
    post:
      summary: |-
        Add a template associated with a user. See :route:`properties/add` to add properties to a file. This
            endpoint can't be called on a team member or admin's behalf.
      operationId: templates/add_for_user
      security:
      - oauth2:
        - files.metadata.write
  /file_properties/templates/add_for_team:
    post:
      summary: |-
        Add a template associated with a team. See :route:`properties/add` to add properties to a file or folder.

            Note: this endpoint will create team-owned templates.
      operationId: templates/add_for_team
      security:
      - oauth2:
        - files.team_metadata.write
  /file_properties/templates/get_for_user:
    post:
      summary: Get the schema for a specified template. This endpoint can't be called on a team member or admin's behalf.
      operationId: templates/get_for_user
      security:
      - oauth2:
        - files.metadata.read
  /file_properties/templates/get_for_team:
    post:
      summary: Get the schema for a specified template.
      operationId: templates/get_for_team
      security:
      - oauth2:
        - files.team_metadata.write
  /file_properties/templates/update_for_user:
    post:
      summary: |-
        Update a template associated with a user. This route can update the template name,
            the template description and add optional properties to templates. This endpoint can't
            be called on a team member or admin's behalf.
      operationId: templates/update_for_user
      security:
      - oauth2:
        - files.metadata.write
  /file_properties/templates/update_for_team:
    post:
      summary: |-
        Update a template associated with a team. This route can update the template name,
            the template description and add optional properties to templates.
      operationId: templates/update_for_team
      security:
      - oauth2:
        - files.team_metadata.write
  /file_properties/templates/list_for_user:
    post:
      summary: |-
        Get the template identifiers for a team. To get the schema of
            each template use :route:`templates/get_for_user`. This endpoint can't be
            called on a team member or admin's behalf.
      operationId: templates/list_for_user
      security:
      - oauth2:
        - files.metadata.read
  /file_properties/templates/list_for_team:
    post:
      summary: |-
        Get the template identifiers for a team. To get the schema of
            each template use :route:`templates/get_for_team`.
      operationId: templates/list_for_team
      security:
      - oauth2:
        - files.team_metadata.write
  /file_properties/templates/remove_for_user:
    post:
      summary: |-
        Permanently removes the specified template created from :route:`templates/add_for_user`.
            All properties associated with the template will also be removed. This action
            cannot be undone.
      operationId: templates/remove_for_user
      security:
      - oauth2:
        - files.metadata.write
  /file_properties/templates/remove_for_team:
    post:
      summary: |-
        Permanently removes the specified template created from :route:`templates/add_for_user`.
            All properties associated with the template will also be removed. This action
            cannot be undone.
      operationId: templates/remove_for_team
      security:
      - oauth2:
        - files.team_metadata.write
  /file_properties/properties/search:
    post:
      summary: Search across property templates for particular property field values.
      operationId: properties/search
      security:
      - oauth2:
        - files.metadata.read
  /file_properties/properties/search/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`properties/search`, use this to paginate through all
            search results.
      operationId: properties/search/continue
      security:
      - oauth2:
        - files.metadata.read
  /sharing/get_shared_link_metadata:
    post:
      summary: Get the shared link's metadata.
      operationId: get_shared_link_metadata
      security:
      - oauth2:
        - sharing.read
  /sharing/list_shared_links:
    post:
      summary: |-
        Returns a list of :type:`LinkMetadata` objects for this user,
            including collection links.

            If no path is given, returns a list of all shared links for the current
            user, including collection links, up to a maximum of 1000 links.

            If a non-empty path is given, returns a list of all shared links
            that allow access to the given path.  Collection links are never
            returned in this case.
      operationId: list_shared_links
      security:
      - oauth2:
        - sharing.read
  /sharing/modify_shared_link_settings:
    post:
      summary: |-
        Modify the shared link's settings.

            If the requested visibility conflict with the shared links policy of the team or the
            shared folder (in case the linked file is part of a shared folder) then the
            :field:`LinkPermissions.resolved_visibility` of the returned :type:`SharedLinkMetadata` will
            reflect the actual visibility of the shared link and the
            :field:`LinkPermissions.requested_visibility` will reflect the requested visibility.
      operationId: modify_shared_link_settings
      security:
      - oauth2:
        - sharing.write
  /sharing/create_shared_link_with_settings:
    post:
      summary: |-
        Create a shared link.

            If a shared link already exists for the given path, that link is returned.

            Previously, it was technically possible to break a shared link by moving or
            renaming the corresponding file or folder. In the future, this will no
            longer be the case, so your app shouldn't rely on this behavior. Instead, if
            your app needs to revoke a shared link, use :route:`revoke_shared_link`.
      operationId: create_shared_link_with_settings
      security:
      - oauth2:
        - sharing.write
  /sharing/revoke_shared_link:
    post:
      summary: |-
        Revoke a shared link.

            Note that even after revoking a shared link to a file, the file may be accessible if there are
            shared links leading to any of the file parent folders. To list all shared links that enable
            access to a specific file, you can use the :route:`list_shared_links` with the file as the
            :field:`ListSharedLinksArg.path` argument.
      operationId: revoke_shared_link
      security:
      - oauth2:
        - sharing.write
  /sharing/get_shared_link_file:
    post:
      summary: Download the shared link's file from a user's Dropbox.
      operationId: get_shared_link_file
      security:
      - oauth2:
        - sharing.read
  /team/sharing_allowlist/add:
    post:
      summary: |-
        Endpoint adds Approve List entries. Changes are effective immediately.
            Changes are committed in transaction. In case of single validation error - all entries are rejected.
            Valid domains (RFC-1034/5) and emails (RFC-5322/822) are accepted.
            Added entries cannot overflow limit of 10000 entries per team.
            Maximum 100 entries per call is allowed.
      operationId: sharing_allowlist/add
      security:
      - oauth2:
        - team_info.write
  /team/sharing_allowlist/list:
    post:
      summary: |-
        Lists Approve List entries for given team, from newest to oldest, returning
            up to `limit` entries at a time. If there are more than `limit` entries
            associated with the current team, more can be fetched by passing the
            returned `cursor` to :route:`sharing_allowlist/list/continue`.
      operationId: sharing_allowlist/list
      security:
      - oauth2:
        - team_info.read
  /team/sharing_allowlist/list/continue:
    post:
      summary: Lists entries associated with given team, starting from a the cursor. See :route:`sharing_allowlist/list`.
      operationId: sharing_allowlist/list/continue
      security:
      - oauth2:
        - team_info.read
  /team/sharing_allowlist/remove:
    post:
      summary: |-
        Endpoint removes Approve List entries. Changes are effective immediately.
            Changes are committed in transaction. In case of single validation error - all entries are rejected.
            Valid domains (RFC-1034/5) and emails (RFC-5322/822) are accepted.
            Entries being removed have to be present on the list.
            Maximum 1000 entries per call is allowed.
      operationId: sharing_allowlist/remove
      security:
      - oauth2:
        - team_info.write
  /account/set_profile_photo:
    post:
      summary: Sets a user's profile photo.
      operationId: set_profile_photo
      security:
      - oauth2:
        - account_info.write
  /team/members/list:2:
    post:
      summary: |-
        Lists members of a team.

            Permission : Team information.
      operationId: members/list:2
      security:
      - oauth2:
        - members.read
  /team/members/list:
    post:
      summary: |-
        Lists members of a team.

            Permission : Team information.
      operationId: members/list
      security:
      - oauth2:
        - members.read
  /team/members/list/continue:2:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`members/list:2`, use this to paginate
            through all team members.

            Permission : Team information.
      operationId: members/list/continue:2
      security:
      - oauth2:
        - members.read
  /team/members/list/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`members/list`, use this to paginate
            through all team members.

            Permission : Team information.
      operationId: members/list/continue
      security:
      - oauth2:
        - members.read
  /team/members/get_info:2:
    post:
      summary: |-
        Returns information about multiple team members.

            Permission : Team information

            This endpoint will return :field:`MembersGetInfoItem.id_not_found`,
            for IDs (or emails) that cannot be matched to a valid team member.
      operationId: members/get_info:2
      security:
      - oauth2:
        - members.read
  /team/members/get_info:
    post:
      summary: |-
        Returns information about multiple team members.

            Permission : Team information

            This endpoint will return :field:`MembersGetInfoItem.id_not_found`,
            for IDs (or emails) that cannot be matched to a valid team member.
      operationId: members/get_info
      security:
      - oauth2:
        - members.read
  /team/members/add:2:
    post:
      summary: |-
        Adds members to a team.

            Permission : Team member management

            A maximum of 20 members can be specified in a single call.

            If no Dropbox account exists with the email address specified, a new Dropbox account will
            be created with the given email address, and that account will be invited to the team.

            If a personal Dropbox account exists with the email address specified in the call,
            this call will create a placeholder Dropbox account for the user on the team and send an
            email inviting the user to migrate their existing personal account onto the team.

            Team member management apps are required to set an initial given_name and surname for a
            user to use in the team invitation and for 'Perform as team member' actions taken on
            the user before they become 'active'.
      operationId: members/add:2
      security:
      - oauth2:
        - members.write
  /team/members/add:
    post:
      summary: |-
        Adds members to a team.

            Permission : Team member management

            A maximum of 20 members can be specified in a single call.

            If no Dropbox account exists with the email address specified, a new Dropbox account will
            be created with the given email address, and that account will be invited to the team.

            If a personal Dropbox account exists with the email address specified in the call,
            this call will create a placeholder Dropbox account for the user on the team and send an
            email inviting the user to migrate their existing personal account onto the team.

            Team member management apps are required to set an initial given_name and surname for a
            user to use in the team invitation and for 'Perform as team member' actions taken on
            the user before they become 'active'.
      operationId: members/add
      security:
      - oauth2:
        - members.write
  /team/members/add/job_status/get:2:
    post:
      summary: |-
        Once an async_job_id is returned from :route:`members/add:2` ,
            use this to poll the status of the asynchronous request.

            Permission : Team member management.
      operationId: members/add/job_status/get:2
      security:
      - oauth2:
        - members.write
  /team/members/add/job_status/get:
    post:
      summary: |-
        Once an async_job_id is returned from :route:`members/add` ,
            use this to poll the status of the asynchronous request.

            Permission : Team member management.
      operationId: members/add/job_status/get
      security:
      - oauth2:
        - members.write
  /team/members/set_profile:2:
    post:
      summary: |-
        Updates a team member's profile.

            Permission : Team member management.
      operationId: members/set_profile:2
      security:
      - oauth2:
        - members.write
  /team/members/set_profile:
    post:
      summary: |-
        Updates a team member's profile.

            Permission : Team member management.
      operationId: members/set_profile
      security:
      - oauth2:
        - members.write
  /team/members/set_profile_photo:2:
    post:
      summary: |-
        Updates a team member's profile photo.

            Permission : Team member management.
      operationId: members/set_profile_photo:2
      security:
      - oauth2:
        - members.write
  /team/members/set_profile_photo:
    post:
      summary: |-
        Updates a team member's profile photo.

            Permission : Team member management.
      operationId: members/set_profile_photo
      security:
      - oauth2:
        - members.write
  /team/members/delete_profile_photo:2:
    post:
      summary: |-
        Deletes a team member's profile photo.

            Permission : Team member management.
      operationId: members/delete_profile_photo:2
      security:
      - oauth2:
        - members.write
  /team/members/delete_profile_photo:
    post:
      summary: |-
        Deletes a team member's profile photo.

            Permission : Team member management.
      operationId: members/delete_profile_photo
      security:
      - oauth2:
        - members.write
  /team/members/get_available_team_member_roles:
    post:
      summary: |-
        Get available TeamMemberRoles for the connected team. To be used with :route:`members/set_admin_permissions:2`.

            Permission : Team member management.
      operationId: members/get_available_team_member_roles
      security:
      - oauth2:
        - members.read
  /team/members/set_admin_permissions:2:
    post:
      summary: |-
        Updates a team member's permissions.

            Permission : Team member management.
      operationId: members/set_admin_permissions:2
      security:
      - oauth2:
        - members.write
  /team/members/set_admin_permissions:
    post:
      summary: |-
        Updates a team member's permissions.

            Permission : Team member management.
      operationId: members/set_admin_permissions
      security:
      - oauth2:
        - members.write
  /team/members/send_welcome_email:
    post:
      summary: |-
        Sends welcome email to pending team member.

            Permission : Team member management

            Exactly one of team_member_id, email, or external_id must be provided to identify the user account.

            No-op if team member is not pending.
      operationId: members/send_welcome_email
      security:
      - oauth2:
        - members.write
  /team/members/remove:
    post:
      summary: |-
        Removes a member from a team.

            Permission : Team member management

            Exactly one of team_member_id, email, or external_id must be provided to identify the user account.

            Accounts can be recovered via :route:`members/recover` for a 7 day period
            or until the account has been permanently deleted or transferred to another account
            (whichever comes first). Calling :route:`members/add` while a user is still recoverable
            on your team will return with :field:`MemberAddResult.user_already_on_team`.

            Accounts can have their files transferred via the admin console for a limited time, based on the version history
            length associated with the team (180 days for most teams).

            This endpoint may initiate an asynchronous job. To obtain the final result
            of the job, the client should periodically poll :route:`members/remove/job_status/get`.
      operationId: members/remove
      security:
      - oauth2:
        - members.delete
  /team/members/remove/job_status/get:
    post:
      summary: |-
        Once an async_job_id is returned from :route:`members/remove` ,
            use this to poll the status of the asynchronous request.

            Permission : Team member management.
      operationId: members/remove/job_status/get
      security:
      - oauth2:
        - members.delete
  /team/members/suspend:
    post:
      summary: |-
        Suspend a member from a team.

            Permission : Team member management

            Exactly one of team_member_id, email, or external_id must be provided to identify the user account.
      operationId: members/suspend
      security:
      - oauth2:
        - members.write
  /team/members/unsuspend:
    post:
      summary: |-
        Unsuspend a member from a team.

            Permission : Team member management

            Exactly one of team_member_id, email, or external_id must be provided to identify the user account.
      operationId: members/unsuspend
      security:
      - oauth2:
        - members.write
  /team/members/recover:
    post:
      summary: |-
        Recover a deleted member.

            Permission : Team member management

            Exactly one of team_member_id, email, or external_id must be provided to identify the user account.
      operationId: members/recover
      security:
      - oauth2:
        - members.delete
  /team/members/move_former_member_files:
    post:
      summary: |-
        Moves removed member's files to a different member. This endpoint initiates an asynchronous job. To obtain the final result
            of the job, the client should periodically poll :route:`members/move_former_member_files/job_status/check`.

            Permission : Team member management.
      operationId: members/move_former_member_files
      security:
      - oauth2:
        - members.write
  /team/members/move_former_member_files/job_status/check:
    post:
      summary: |-
        Once an async_job_id is returned from :route:`members/move_former_member_files` ,
            use this to poll the status of the asynchronous request.

            Permission : Team member management.
      operationId: members/move_former_member_files/job_status/check
      security:
      - oauth2:
        - members.write
  /team/legal_holds/create_policy:
    post:
      summary: |-
        Creates new legal hold policy.
            Note: Legal Holds is a paid add-on. Not all teams have the feature.

            Permission : Team member file access.
      operationId: legal_holds/create_policy
      security:
      - oauth2:
        - team_data.governance.write
  /team/legal_holds/get_policy:
    post:
      summary: |-
        Gets a legal hold by Id.
            Note: Legal Holds is a paid add-on. Not all teams have the feature.

            Permission : Team member file access.
      operationId: legal_holds/get_policy
      security:
      - oauth2:
        - team_data.governance.write
  /team/legal_holds/list_policies:
    post:
      summary: |-
        Lists legal holds on a team.
            Note: Legal Holds is a paid add-on. Not all teams have the feature.

            Permission : Team member file access.
      operationId: legal_holds/list_policies
      security:
      - oauth2:
        - team_data.governance.write
  /team/legal_holds/list_held_revisions:
    post:
      summary: |-
        List the file metadata that's under the hold.
            Note: Legal Holds is a paid add-on. Not all teams have the feature.

            Permission : Team member file access.
      operationId: legal_holds/list_held_revisions
      security:
      - oauth2:
        - team_data.governance.write
  /team/legal_holds/list_held_revisions_continue:
    post:
      summary: |-
        Continue listing the file metadata that's under the hold.
            Note: Legal Holds is a paid add-on. Not all teams have the feature.

            Permission : Team member file access.
      operationId: legal_holds/list_held_revisions_continue
      security:
      - oauth2:
        - team_data.governance.write
  /team/legal_holds/update_policy:
    post:
      summary: |-
        Updates a legal hold.
            Note: Legal Holds is a paid add-on. Not all teams have the feature.

            Permission : Team member file access.
      operationId: legal_holds/update_policy
      security:
      - oauth2:
        - team_data.governance.write
  /team/legal_holds/release_policy:
    post:
      summary: |-
        Releases a legal hold by Id.
            Note: Legal Holds is a paid add-on. Not all teams have the feature.

            Permission : Team member file access.
      operationId: legal_holds/release_policy
      security:
      - oauth2:
        - team_data.governance.write
  /sharing/list_folders:
    post:
      summary: Return the list of all shared folders the current user has access to.
      operationId: list_folders
      security:
      - oauth2:
        - sharing.read
  /sharing/list_folders/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`list_folders`, use this to paginate through all
            shared folders. The cursor must come from a previous call to :route:`list_folders` or
            :route:`list_folders/continue`.
      operationId: list_folders/continue
      security:
      - oauth2:
        - sharing.read
  /sharing/list_mountable_folders:
    post:
      summary: Return the list of all shared folders the current user can mount or unmount.
      operationId: list_mountable_folders
      security:
      - oauth2:
        - sharing.read
  /sharing/list_mountable_folders/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`list_mountable_folders`, use this to paginate through all
            mountable shared folders. The cursor must come from a previous call to :route:`list_mountable_folders` or
            :route:`list_mountable_folders/continue`.
      operationId: list_mountable_folders/continue
      security:
      - oauth2:
        - sharing.read
  /sharing/get_folder_metadata:
    post:
      summary: Returns shared folder metadata by its folder ID.
      operationId: get_folder_metadata
      security:
      - oauth2:
        - sharing.read
  /sharing/list_folder_members:
    post:
      summary: Returns shared folder membership by its folder ID.
      operationId: list_folder_members
      security:
      - oauth2:
        - sharing.read
  /sharing/list_folder_members/continue:
    post:
      summary: |-
        Once a cursor has been retrieved from :route:`list_folder_members`, use this to paginate
            through all shared folder members.
      operationId: list_folder_members/continue
      security:
      - oauth2:
        - sharing.read
  /sharing/share_folder:
    post:
      summary: |-
        Share a folder with collaborators.

            Most sharing will be completed synchronously. Large folders will be
            completed asynchronously. To make testing the async case repeatable, set
            `ShareFolderArg.force_async`.

            If a :field:`ShareFolderLaunch.async_job_id` is returned, you'll need to
            call :route:`check_share_job_status` until the action completes to get the
            metadata for the folder.
      operationId: share_folder
      security:
      - oauth2:
        - sharing.write
  /sharing/check_share_job_status:
    post:
      summary: Returns the status of an asynchronous job for sharing a folder.
      operationId: check_share_job_status
      security:
      - oauth2:
        - sharing.write
  /sharing/check_job_status:
    post:
      summary: Returns the status of an asynchronous job.
      operationId: check_job_status
      security:
      - oauth2:
        - sharing.write
  /sharing/unshare_folder:
    post:
      summary: |-
        Allows a shared folder owner to unshare the folder.

            You'll need to call :route:`check_job_status` to determine if the action has
            completed successfully.
      operationId: unshare_folder
      security:
      - oauth2:
        - sharing.write
  /sharing/transfer_folder:
    post:
      summary: |-
        Transfer ownership of a shared folder to a member of the shared folder.

            User must have :field:`AccessLevel.owner` access to the shared folder to perform a transfer.
      operationId: transfer_folder
      security:
      - oauth2:
        - sharing.write
  /sharing/update_folder_policy:
    post:
      summary: |-
        Update the sharing policies for a shared folder.

            User must have :field:`AccessLevel.owner` access to the shared folder to update its policies.
      operationId: update_folder_policy
      security:
      - oauth2:
        - sharing.write
  /sharing/add_folder_member:
    post:
      summary: |-
        Allows an owner or editor (if the ACL update policy allows) of a shared
            folder to add another member.

            For the new member to get access to all the functionality for this folder,
            you will need to call :route:`mount_folder` on their behalf.
      operationId: add_folder_member
      security:
      - oauth2:
        - sharing.write
  /sharing/remove_folder_member:
    post:
      summary: |-
        Allows an owner or editor (if the ACL update policy allows) of a shared
            folder to remove another member.
      operationId: remove_folder_member
      security:
      - oauth2:
        - sharing.write
  /sharing/check_remove_member_job_status:
    post:
      summary: Returns the status of an asynchronous job for sharing a folder.
      operationId: check_remove_member_job_status
      security:
      - oauth2:
        - sharing.write
  /sharing/update_folder_member:
    post:
      summary: |-
        Allows an owner or editor of a shared folder to update another member's
            permissions.
      operationId: update_folder_member
      security:
      - oauth2:
        - sharing.write
  /sharing/mount_folder:
    post:
      summary: |-
        The current user mounts the designated folder.

            Mount a shared folder for a user after they have been added as a member.
            Once mounted, the shared folder will appear in their Dropbox.
      operationId: mount_folder
      security:
      - oauth2:
        - sharing.write
  /sharing/unmount_folder:
    post:
      summary: |-
        The current user unmounts the designated folder. They can re-mount the
            folder at a later time using :route:`mount_folder`.
      operationId: unmount_folder
      security:
      - oauth2:
        - sharing.write
  /sharing/relinquish_folder_membership:
    post:
      summary: |-
        The current user relinquishes their membership in the designated shared
            folder and will no longer have access to the folder.  A folder owner cannot
            relinquish membership in their own folder.

            This will run synchronously if leave_a_copy is false, and asynchronously
            if leave_a_copy is true.
      operationId: relinquish_folder_membership
      security:
      - oauth2:
        - sharing.write
  /sharing/set_access_inheritance:
    post:
      summary: |-
        Change the inheritance policy of an existing Shared Folder. Only permitted for shared folders in a shared team root.

            If a :field:`ShareFolderLaunch.async_job_id` is returned, you'll need to
            call :route:`check_share_job_status` until the action completes to get the
            metadata for the folder.
      operationId: set_access_inheritance
      security:
      - oauth2:
        - sharing.write
  /team/member_space_limits/set_custom_quota:
    post:
      summary: |-
        Set users custom quota. Custom quota has to be at least 15GB.
            A maximum of 1000 members can be specified in a single call.
            Note: to apply a custom space limit, a team admin needs to set a member space limit for the team first.
            (the team admin can check the settings here: https://www.dropbox.com/team/admin/settings/space).
      operationId: member_space_limits/set_custom_quota
      security:
      - oauth2:
        - members.read
  /team/member_space_limits/remove_custom_quota:
    post:
      summary: |-
        Remove users custom quota.
            A maximum of 1000 members can be specified in a single call.
            Note: to apply a custom space limit, a team admin needs to set a member space limit for the team first.
            (the team admin can check the settings here: https://www.dropbox.com/team/admin/settings/space).
      operationId: member_space_limits/remove_custom_quota
      security:
      - oauth2:
        - members.write
  /team/member_space_limits/get_custom_quota:
    post:
      summary: |-
        Get users custom quota.
            A maximum of 1000 members can be specified in a single call.
            Note: to apply a custom space limit, a team admin needs to set a member space limit for the team first.
            (the team admin can check the settings here: https://www.dropbox.com/team/admin/settings/space).
      operationId: member_space_limits/get_custom_quota
      security:
      - oauth2:
        - members.read
  /team/member_space_limits/excluded_users/add:
    post:
      summary: Add users to member space limits excluded users list.
      operationId: member_space_limits/excluded_users/add
      security:
      - oauth2:
        - members.write
  /team/member_space_limits/excluded_users/remove:
    post:
      summary: Remove users from member space limits excluded users list.
      operationId: member_space_limits/excluded_users/remove
      security:
      - oauth2:
        - members.write
  /team/member_space_limits/excluded_users/list:
    post:
      summary: List member space limits excluded users.
      operationId: member_space_limits/excluded_users/list
      security:
      - oauth2:
        - members.read
  /team/member_space_limits/excluded_users/list/continue:
    post:
      summary: Continue listing member space limits excluded users.
      operationId: member_space_limits/excluded_users/list/continue
      security:
      - oauth2:
        - members.read
  /team/members/secondary_emails/add:
    post:
      summary: |-
        Add secondary emails to users.

            Permission : Team member management.

            Emails that are on verified domains will be verified automatically.
            For each email address not on a verified domain a verification email will be sent.
      operationId: members/secondary_emails/add
      security:
      - oauth2:
        - members.write
  /team/members/secondary_emails/resend_verification_emails:
    post:
      summary: |-
        Resend secondary email verification emails.

            Permission : Team member management.
      operationId: members/secondary_emails/resend_verification_emails
      security:
      - oauth2:
        - members.write
  /team/members/secondary_emails/delete:
    post:
      summary: |-
        Delete secondary emails from users

            Permission : Team member management.

            Users will be notified of deletions of verified secondary emails at both the secondary email and their primary email.
      operationId: members/secondary_emails/delete
      security:
      - oauth2:
        - members.write
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.dropbox.com/oauth2/authorize
          tokenUrl: https://api.dropboxapi.com/oauth2/token
          scopes:
            sharing.read: Access to sharing.read operations
            account_info.read: Access to account info.read operations
            sessions.list: Access to sessions.list operations
            sessions.modify: Access to sessions.modify operations
            groups.read: Access to groups.read operations
            groups.write: Access to groups.write operations
            openid: Access to openid operations
            sharing.write: Access to sharing.write operations
            events.read: Access to events.read operations
            team_data.content.write: Access to team data.content.write operations
            team_data.content.read: Access to team data.content.read operations
            files.metadata.write: Access to files.metadata.write operations
            files.metadata.read: Access to files.metadata.read operations
            file_requests.read: Access to file requests.read operations
            file_requests.write: Access to file requests.write operations
            files.content.write: Access to files.content.write operations
            files.permanent_delete: Access to files.permanent delete operations
            files.content.read: Access to files.content.read operations
            team_data.member: Access to team data.member operations
            team_info.read: Access to team info.read operations
            files.team_metadata.write: Access to files.team metadata.write operations
            contacts.write: Access to contacts.write operations
            team_info.write: Access to team info.write operations
            account_info.write: Access to account info.write operations
            members.read: Access to members.read operations
            members.write: Access to members.write operations
            members.delete: Access to members.delete operations
            team_data.governance.write: Access to team data.governance.write operations